version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      # Install poetry
      # https://python-poetry.org/docs/#installing-manually
      - python -m pip install poetry
    post_install:
      # Install dependencies with 'docs' dependency group
      # https://python-poetry.org/docs/managing-dependencies/#dependency-groups
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --with dev

    pre_build:
      # Generate latest various flowcharts
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH python mirar/utils/docs/pipeline_visualisation.py
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH python mirar/utils/docs/auto_config_docs.py
      # Generate API documentation
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry run sphinx-apidoc -o ./docs/source/ ./mirar --module-first --force

sphinx:
  builder: html
  fail_on_warning: false
  configuration: docs/source/conf.py

formats:
  - epub
