CREATE TABLE IF NOT EXISTS raw ( rawid SERIAL PRIMARY KEY, FILENAME VARCHAR(255) NOT NULL, OBSDATE INT,
	FILESIZE REAL, OBJECT VARCHAR(30), OBJ_RA FLOAT, OBJ_DEC FLOAT, TEL_RA FLOAT, TEL_DEC FLOAT, HA FLOAT,
	AIRMASS FLOAT, ALT FLOAT, AZ FLOAT, MOON_ANGLE FLOAT, FIELD_ID VARCHAR(30), FOCUSER_POSITION FLOAT,
	ROT_FIELD_ANGLE FLOAT, ROT_POSITION FLOAT, DOME_AZ FLOAT, DOME_SHUTTER VARCHAR(5), FILTER VARCHAR(5),
	EXP_START_MJD FLOAT, EXPTIME FLOAT, CCD_TEMP FLOAT, CCD_GAIN FLOAT, CCD_READOUT_FREQ FLOAT, CAMERA VARCHAR(15),
	OBSTYPE VARCHAR(15) , PROGID INT FOREIGN KEY REFERENCES programs(progid) );