CREATE TABLE IF NOT EXISTS proc (
    procid BIGINT PRIMARY KEY,
    expid BIGINT,
    rawpath VARCHAR(255),
    savepath VARCHAR(255),
    OBSDATE INT,
    timeutc TIMESTAMPTZ,
    FILTER VARCHAR(10),
    EXPTIME REAL,
    fieldID VARCHAR(30),
    CD1_1 REAL,
    CD1_2 REAL,
    CD2_1 REAL,
    CD2_2 REAL,
    CRVAL1 REAL,
    CRVAL2 REAL,
    CRPIX1 REAL,
    CRPIX2 REAL,
    ZP_AUTO REAL,
    FWHM_MED REAL,
    FWHM_STD REAL,
    flatname VARCHAR(255),
    biasname VARCHAR(255),
    ASTR_DPA FLOAT,
    ASTR_OFF FLOAT,
    ZP_AUTO_NSTARS INT,
    ZP_AUTO_STD FLOAT,
    OBSMJD FLOAT,
    progid INT,
    proccount SERIAL,
    MAGLIM REAL,
    CONSTRAINT fk_expid
            FOREIGN KEY(expid)
                REFERENCES raw(expid)
);
