CREATE TABLE IF NOT EXISTS proc ( procid SERIAL PRIMARY KEY, rawid SERIAL, RAW_IMAGENAME VARCHAR(255),
	PROC_IMAGENAME VARCHAR(255), OBSDATE INT, FILTER VARCHAR(10),  EXPTIME INT, FIELD_ID VARCHAR(30), CD1_1 REAL,
	CD1_2 REAL, CD2_1 REAL, CD2_2 REAL, CRVAL1 REAL, CRVAL2 REAL, CRPIX1 REAL, CRPIX2 REAL, ZP REAL, FWHM REAL,
	MAGLIM REAL, FLATFILENAME VARCHAR(255), DARKFILENAME VARCHAR(255), BIASFILENAME VARCHAR(255), ASTR_DPA FLOAT,
	ASTR_OFF FLOAT, FLXSCALE FLOAT, PV1_0 FLOAT, PV1_1 FLOAT, PV1_4 FLOAT, PV1_7 FLOAT, PV2_0 FLOAT, PV2_1 FLOAT,
	PV2_2 FLOAT, PV2_6 FLOAT, PV2_10 FLOAT, ZP_NSTARS INT, ZP_STD FLOAT, EXP_MJD FLOAT, PROGID INT FOREIGN KEY
	REFERENCES programs(progid);
	);