name: Install script

on:
  push:
  pull_request:
  merge_group:
  schedule:
    - cron: '0 0 1,15 * *'
  workflow_dispatch:

jobs:
  test_install:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-15, ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          auto-update-conda: true

      - name: Run install script
        run: |
          bash install_mirar.sh mirar

      - name: Activate mirar environment
        run: echo "CONDA_DEFAULT_ENV=mirar" >> $GITHUB_ENV

      - name: Verify tools
        shell: bash -el {0}
        run: |
          solve-field --version
          swarp -v
          psfex -v
          sex -v
          scamp -v
          python --version

      - name: Run doc tests
        shell: bash -el {0}
        run: |
          poetry run make -C docs/ doctest
